### ISSUE TITLE
Not able to build for web anymore since including this library

### ISSUE THREAD

**Issue by masewo** [dart-windows/filepicker_windows#11]
When adding filepicker_windows to the pubspec.yaml then apps are not able to run/build for web anymore.

filepicker_windows: 2.0.0
Flutter 2.0.5

Build output:
```
Pub/Cache/hosted/pub.dartlang.org/filepicker_windows-2.0.0/lib/src/directorydialog.dart:1:8: Error: Not found: 'dart:ffi'
import 'dart:ffi';
       ^
```

**Comment by harbignote** [comment]
> When adding filepicker_windows to the pubspec.yaml then apps are not able to run/build for web anymore.
> 
> filepicker_windows: 2.0.0
> Flutter 2.0.5
> 
> Build output:
> 
> ```
> Pub/Cache/hosted/pub.dartlang.org/filepicker_windows-2.0.0/lib/src/directorydialog.dart:1:8: Error: Not found: 'dart:ffi'
> import 'dart:ffi';
>        ^
> ```

The web is not support yet  - search for something else
