### ISSUE TITLE
Shortcut doesn't open

### ISSUE THREAD

**Issue by aampor-12** [dart-windows/filepicker_windows#27]
when I chose a shortcut it says : catastrophic failure

can you fix it please

Thank you for the great Package,

**Comment by halildurmus** [comment]
It works on my machine. Could you please share the code you're using?

Here's the one I used:
```dart
import 'package:filepicker_windows/filepicker_windows.dart';

void main() {
  final file = OpenFilePicker()..title = 'Select a file';

  final result = file.getFile();
  if (result != null) {
    print(result.path);
  }
}

```

**Comment by aampor-12** [comment]
that's my code : 

roby() {
  final file = OpenFilePicker()..title = 'select a file';

  final result = file.getFile();
  if (result != null) {
    return result.path;
  }
}
![catastrophic failure](https://github.com/dart-windows/filepicker_windows/assets/119249438/2b0ebeb1-1b49-490b-9dab-b22fe35238da)

**Comment by halildurmus** [comment]
Interesting, I have no idea why it doesn't work on your machine.

![ss](https://github.com/dart-windows/filepicker_windows/assets/45524029/d44da3d1-ec08-4841-97da-c1072aff3e79)

**Comment by halildurmus** [comment]
I found [this](https://stackoverflow.com/questions/60739608/why-does-openfiledialog-say-path-does-not-exist-or-catastrophic-error-after) on StackOverflow, which seems to be the same issue you're experiencing.

The answer got me thinking, can you clone this repository and add this line
 ```dart
options |= FILEOPENDIALOGOPTIONS.FOS_NODEREFERENCELINKS;
```
to `open_file_picker.dart` and run the example?

![Screenshot 2024-02-04 223629](https://github.com/dart-windows/filepicker_windows/assets/45524029/f3b7c5b1-edef-45b4-bd6b-99c66d0766bf)

**Comment by halildurmus** [comment]
Just published a new version that has a new field: `dereferenceLinks`. By setting it to `false`, you can now directly open the shortcut file without resolving its target if that's what you want.
